# Generated by Django 6.0.3 on 2026-04-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=100)),
                ('requirements', models.TextField()),
                ('about_company', models.TextField()),
                ('job_type', models.CharField(max_length=50)),
                ('benefit', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('job_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
