# Generated by Django 5.0.1 on 2026-04-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
    ]
