# Generated by Django 5.0.1 on 2026-04-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_user_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="applied_jobs",
            field=models.ManyToManyField(
                blank=True, related_name="applied_by", to="api.job"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="saved_jobs",
            field=models.ManyToManyField(
                blank=True, related_name="saved_by", to="api.job"
            ),
        ),
    ]
